//This file was generated by script swreg2regmap.py

//register address mapping
#define KNN_RESET 0
#define KNN_ENABLE 1
#define KNN_A 2
#define KNN_B 3
#define KNN_LABEL 4
#define KNN_INFO0 5
#define KNN_INFO1 6
#define KNN_INFO2 7
#define KNN_INFO3 8
#define KNN_INFO4 9
#define KNN_INFO5 10
#define KNN_INFO6 11
#define KNN_INFO7 12
#define KNN_INFO8 13
#define KNN_INFO9 14
